### ISSUE TITLE
.ical: Link, Cancelled Events

### ISSUE THREAD

**Issue by haslo** [Yoshi20/SSB-Tournament-Manager#13]
#### Link

Wenn der .ics-Export schon läuft, könnte der auch zum Abonnieren angepriesen werden.

http://ssb-tournament-manager.herokuapp.com/calendar.ics

#### Cancelled Events

Gemäss https://tools.ietf.org/html/rfc5545#section-3.8.1.11, um `app/models/calendar.rb#104`:

```ruby
if tournament.cancelled?
  event.status = 'CANCELLED'
end
```

...dann werden die nicht aktiven Ereignisse von Kalender-Clients korrekt angezeigt.

**Comment by Yoshi20** [comment]
https://github.com/Yoshi20/SSB-Tournament-Manager/pull/14
