### ISSUE TITLE
crash reports -> rollbar?

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/SSB-Tournament-Manager#61]
Oder zumindest den Error text (We're sorry, but something went wrong.) ändern

**Comment by haslo** [comment]
Fehler ändern => `public/500.html`

**Comment by haslo** [comment]
Oh, und statt Rollbar (das kostet) könntest Du was wie das hier verwenden:

https://github.com/smartinez87/exception_notification

**Comment by Yoshi20** [comment]
Merci haslo :)
